import 'package:road_trip_colombia/ui/pages/list_page/departamento.dart';

const listMock = <Departamento>[
  Departamento(
      id: 1,
      name: "Amazonas",
      capital: " Leticia  ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 2,
      name: "Antioquía",
      capital: " Medellín ",
      image: "assets/images/2.jpg",
      description: ""),
  Departamento(
      id: 3,
      name: "Arauca",
      capital: " Arauca ",
      image: "assets/images/3.jpg",
      description: ""),
  Departamento(
      id: 4,
      name: "Atlántico",
      capital: " Barranquilla ",
      image: "assets/images/4.jpg",
      description: ""),
  Departamento(
      id: 5,
      name: "Bolívar",
      capital: " Cartagena de Indias ",
      image: "assets/images/5.jpg",
      description: ""),
  Departamento(
      id: 6,
      name: "Boyacá",
      capital: " Tunja ",
      image: "assets/images/6.jpg",
      description: ""),
  Departamento(
      id: 7,
      name: "Caldas",
      capital: " Manizales ",
      image: "assets/images/7.jpg",
      description: ""),
  Departamento(
      id: 8,
      name: "Caquetá",
      capital: " Florencia ",
      image: "assets/images/8.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Casanare",
      capital: " Yopal ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Cauca",
      capital: " Popayán ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Cesar",
      capital: " Valledupar ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Chocó",
      capital: " Quibdó ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Córdoba",
      capital: " Montería ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Cundinamarca",
      capital: " Bogotá ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Guainía",
      capital: " Inírida ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Guaviare",
      capital: " San José del Guaviare ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Huila",
      capital: " Neiva ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "La Guajira",
      capital: " Riohacha ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Magdalena",
      capital: " Santa Marta ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Meta",
      capital: " Villavicencio ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Nariño",
      capital: " San Juan de Pasto ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Norte de Santander",
      capital: " San José de Cúcuta ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Putumayo",
      capital: " Mocoa ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Quindío",
      capital: " Armenia ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Risaralda",
      capital: " Pereira ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "San Andrés y Providencia",
      capital: " San Andrés ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Santander",
      capital: " Bucaramanga ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Sucre",
      capital: " Sincelejo ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Tolima",
      capital: " Ibagué ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Valle del Cauca",
      capital: " Cali ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Vaupés",
      capital: " Mitú ",
      image: "assets/images/1.jpg",
      description: ""),
  Departamento(
      id: 1,
      name: "Vichada",
      capital: " Puerto Carreño ",
      image: "assets/images/1.jpg",
      description: ""),
];
